### ISSUE TITLE
Can't get past disclaimer screen on smartwatch

### ISSUE THREAD

**Issue by ir-fuel** [Nanoux/Onewave#4]
Hello

I am trying to run your app on a LEMFO LEM4 PRO Android watch, but I am stuck on the disclaimer screen. I presume I need to tap a button but it's simply not visible.

You think you could fix this?

Thanks
![IMG_7428](https://user-images.githubusercontent.com/1573715/63636249-49004480-c66d-11e9-9ab8-b5fdd33c151d.JPG)

**Comment by Nanoux** [comment]
If your running the newest version you should be able to scroll to a button at the bottom. Sorry for the late reply. You may run into problems elsewhere, I didn't know you could run Android apps like that 0_0

**Comment by ir-fuel** [comment]
This is the latest version on the App Store. Unless there has been a newer one in the last 9 days?

**Comment by Nanoux** [comment]
The app store version got falsely DMCAd and is no longer updated, you have to download the apk from the releases tab on this GitHub page. Latest version is 2.1
