### ISSUE TITLE
Can't get passed Disclamer page on Android Phone

### ISSUE THREAD

**Issue by bmfy01** [Nanoux/Onewave#7]
I can't find a button to get past the disclaimer page on my Android phone. I tried scrolling but there isn't anywhere to scroll.

**Comment by Nanoux** [comment]
Are you on the latest version? That's been fixed for a while. The play store version isn't updated anymore you gave to download an app from the releases tab on this page

**Comment by bmfy01** [comment]
Yes, I am on version 2.1 downloaded from Github

**Comment by Nanoux** [comment]
Screenshot? It works fine for me

**Comment by bmfy01** [comment]
![Onewave Screenshot](https://user-images.githubusercontent.com/58894246/70954551-8759af00-2022-11ea-9885-199a588153a7.png)
I can press hidden buttons to change the theme of the background as well. I am also on Android 8 if that helps

**Comment by Nanoux** [comment]
Well I thought I fixed that, I guess not, I'll look into it. In the mean time your system font size is ludicrously large, if you lower it, the button should come on screen, you can accept it, and then increase the font size again. You may run into problems elsewhere in the app tho.

**Comment by bmfy01** [comment]
Yes, thank you. I shrunk the text size and the disclaimer button showed up. Thank you for your time. The program works great. I can also confirm that the program works on the pint, however sometimes the connection times out and won't reconnect until a power cycle on the onewheel, or a restart of the phone.

**Comment by Nanoux** [comment]
It does!? It doesn't work on my pint. Also you should just be able to toggle Bluetooth on and off to fix that, don't have to restart your whole phone.

**Comment by bmfy01** [comment]
True, thank you. I wonder why the program doesn't work on your pint tho

**Comment by bmfy01** [comment]
Also, not all of the features work when connected to the pint. The speedometer works fine and so does the digistal shaping (although they are the onewheel XR shaping names, still works though). The battery cell voltage doesn't work however. Great app, just FYI to pint users.
